### ISSUE TITLE
Coquille à la page 12

### ISSUE THREAD

**Issue by aexerces** [exo7math/quantum-exo7#1]
Bonjour, 
Je me permets d'ouvrir une issue car je ne sais pas trop comment vous contacter.
C'est à propos d'une petite coquille. J'ai trouvé l'erreur dans le fichier source: "decouverte.tex", à la ligne 753. Je pense que le dernier "ket" est plutôt un "ket-1", et non "ket-0", pour la formule de l'état de Bell.
Je débute votre livre et je vous remercie pour ce travail :)

**Comment by arnbod** [comment]
Merci. C'est corrigé.
