### ISSUE TITLE
Erreur dans Découverte 3.4

### ISSUE THREAD

**Issue by zigtur** [exo7math/quantum-exo7#3]
Bonjour,
J'ouvre une issue car je pense qu'il y a une erreur à la ligne 837 du fichier decouverte.tex : 
Erreur : |(0 + 1).1〉 = |0.0〉 + |0.1〉
Correction : |(0 + 1).1〉 = |0.1〉 + |1.1〉

Merci beaucoup pour ce livre de qualité ;)

https://github.com/exo7math/quantum-exo7/blob/3132b43a0625d4183559db5a441752c86ddac1a0/decouverte/decouverte.tex#L837

**Comment by arnbod** [comment]
Merci! C'est corrigé.
